openapi: 3.0.1
info:
  title: Urban Plugin
  description: A plugin that allows the user to find new and off-the-plan apartments and townhome around Australia.
  version: "v1"
servers:
  - url: https://api.urban.com.au/openai
paths:
  /apartments:
    get:
      operationId: getApartments
      summary: Get the list of apartments based on the query parameters
      parameters:
        - in: query
          name: address
          schema:
            type: string
          required: false
          description: The Address of the apartment
        - in: query
          name: suburb
          schema:
            type: string
          required: false
          description: The Suburb of the apartment
        - in: query
          name: state
          schema:
            type: string
          required: false
          description: The State of the apartment
        - in: query
          name: price_min
          schema:
            type: number
          required: false
          description: The Minimum Price of an Apartment
        - in: query
          name: price_max
          schema:
            type: number
          required: false
          description: The Maximum Price of an Apartment
        - in: query
          name: bedroom_min
          schema:
            type: number
          required: false
          description: The Minimum number of Bedroom of an Apartment
        - in: query
          name: bedroom_max
          schema:
            type: number
          required: false
          description: The Maximum number of Bedroom of an Apartment
        - in: query
          name: parking_min
          schema:
            type: number
          required: false
          description: The Minimum number of Parking slot of an Apartment
        - in: query
          name: parking_max
          schema:
            type: number
          required: false
          description: The Maximum number of Parking slot of an Apartment
        - in: query
          name: bathroom_min
          schema:
            type: number
          required: false
          description: The Minimum number of Bathroom of an Apartment
        - in: query
          name: bathroom_max
          schema:
            type: number
          required: false
          description: The Maximum number of Bathroom of an Apartment

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getApartmentsResponse"
components:
  schemas:
    getApartmentsResponse:
      type: array
      items:
        type: object
        properties:
          title:
            type: string
            description: The title of the apartment.
          description:
            type: string
            description: The description of the apartment.
          floor_count:
            type: string
            description: The Floor count of the apartment's building.
          address:
            type: string
            description: The Full address of the apartment.
          suburb:
            type: string
            description: The Suburb of the apartment.
          state:
            type: string
            description: The State of the apartment.
          url:
            type: string
            description: The Website URL of the apartment.
          apartments:
            type: array
            items:
              type: object
              properties:
                bedrooms:
                  type: string
                  description: The Number of Bedrooms of the apartment.
                bathrooms:
                  type: string
                  description: The Number of Bathrooms of the apartment.
                parking:
                  type: string
                  description: The Number of Parking slot of the apartment.
                price:
                  type: string
                  description: The Price of the apartment.
