openapi: 3.0.1
info:
  title: ChatSpot
  description: A plugin for an AI assistant called ChatSpot that helps users interact with their HubSpot CRM and many other SAAS tools.
  version: 'v1'
servers:
  - url: https://do2.chatspot.ai/plugin
paths:
  /chat:
    post:
      operationId: chat
      summary: Send a message to ChatSpot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/chatRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/chatResponse'

components:
  schemas:
    chatRequest:
      type: object
      required:
      - message
      properties:
        message:
          type: string
          description: The entire message sent by the user when invoking this plugin
          required: true
    chatResponse:
      type: object
      properties:
        response:
          type: string
          description: The text component of a ChatSpot response
        data_table:
          type: array
          items:
            type: array
            items: {}
          description: A two-dimensional array representing the data table component of a ChatSpot response
