openapi: 3.1.0
info:
  title: Boolio ChatGPT plugin
  version: 2023.5.3
paths:
  /api/stock/summary:
    get:
      summary: Summarize stock info
      description: Summarize stock info of the given country and ticker
      operationId: getApiStockSummary
      parameters:
      - name: region
        in: query
        description: An ISO-3166-1 alpha-2 code of the country
        required: true
        schema:
          type: string
        examples:
          Example0:
            value: US
          Example1:
            value: KR
          Example2:
            value: JP
      - name: symbol
        in: query
        description: The identifier of the stock in the corresponding region
        required: true
        schema:
          type: string
        examples:
          Apple:
            summary: 'Ticker of Apple. (region: US)'
            value: AAPL
          Samsung Electronics:
            summary: 'Ticker of Samsung Electronics. (region: KR)'
            value: '005930'
          Reliance Industries Limited:
            summary: 'Ticker of Reliance Industries Limited. (region: IN)'
            value: 500325
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: 'Invalid value for: query parameter region, Invalid value for:
            query parameter symbol'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: ''
          content:
            text/plain:
              schema:
                type: string
