openapi: 3.0.1
info:
  title: Bramework Plugin
  description: Boost SEO with keyword insights on search volume, ranking difficulty, and SERP analysis.
  version: 'v1'
servers:
  - url: https://plugin.bramework.com
paths:
  /keyword-data:
    post:
      operationId: keywordData
      summary: Get keyword data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - keyword
              properties:
                keyword:
                  type: string
                  description: The keyword to analyze.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: The keyword data.
  /related-keywords:
    post:
      operationId: relatedKeywords
      summary: Get related keywords
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - keyword
              properties:
                keyword:
                  type: string
                  description: The keyword to find related keywords for.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  related_keywords:
                    type: array
                    items:
                      type: string
                    description: The related keywords.
