openapi: 3.0.1
info:
  title: Speechki ChatGPT Text-to-Audio Conversion API
  description: Convert ChatGPT-generated English content into high-quality, human-like audio files using Speechki's text-to-speech platform API. Exclusively supporting English language, Speechki provides access to a wide range of artificial voices, accents, and emotions, ensuring a personalized and immersive listening experience with the lowest time and cost of audio production.
  version: 'v1'
servers:
  - url: https://plugin.speechki.org
paths:
  /api/openai/speakers/samples:
    get:
      operationId: get-speakers-samples
      summary: Gets the link to the list of available artificial voices for text-to-speech conversion, including detailed information about each voice, such as the voice ID, speaker's name, language, gender, and narration style.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpeakersSample'
  /api/openai/tts:
    post:
      operationId: tts
      summary: Send ChatGPT-generated text to the Speechki platform to convert it into a high-quality audio file using advanced text-to-speech services.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TTSData'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TTSResponse'
components:
  schemas:
    SpeakersSample:
      type: object
      properties:
        message:
          type: string
          description: The link to the list of available voices
      description: The link to the comprehensive list of artificial voices available on the Speechki platform.
    TTSData:
      type: object
      required: [ "text" ]
      properties:
        speaker_id:
          type: integer
          description: A unique identifier representing a specific artificial voice provided by the Speechki platform.
        text:
          type: string
          description: The input text, either provided by the user or generated by ChatGPT, is sent to the Speechki platform for conversion into a high-quality audio file using advanced text-to-speech services.
    TTSResponse:
      type: object
      properties:
        link:
          type: string
          description: The direct link to the Speechki platform's page containing the ready-to-use audio file, which has been converted from ChatGPT-generated text using advanced text-to-speech services.
