openapi: 3.0.2
info:
  title: Speechki ChatGPT Text-to-Audio Conversion API
  description: Convert ChatGPT-generated English content into high-quality, human-like audio files using Speechki's text-to-speech platform API. Exclusively supporting English language, Speechki provides access to a wide range of artificial voices, accents, and emotions, ensuring a personalized and immersive listening experience with the lowest time and cost of audio production.
  version: 'v1'
servers:
  - url: https://plugin.speechki.org
paths:
  /api/openai/speakers:
    get:
      operationId: get-speakers
      summary: Gets the list of available artificial voices for text-to-speech conversion, including detailed information about each voice, such as the voice ID, speaker's name, language, gender, and narration style. This endpoint helps users to select the most suitable voice for their ChatGPT-generated content.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpeakersList'
  /api/openai/tts:
    post:
      operationId: tts
      summary: Send ChatGPT-generated text to the Speechki platform to convert it into a high-quality audio file using advanced text-to-speech services.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TTSData'
      responses:
        "200":
          descrition: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TTSResponse'
components:
  schemas:
    SpeakersList:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            description: Unique identificator of speaker
          name:
            type: string
            description: The descriptive name associated with a specific artificial voice on the Speechki platform. Users can refer to speaker names as a more human-readable reference when selecting the most suitable voice for converting their ChatGPT-generated text into high-quality audio files.
          language:
            type: string
            description: The language spoken by a specific artificial voice on the Speechki platform. Each voice is associated with a particular language, enabling users to choose the most appropriate voice for converting their ChatGPT-generated text.
          tags:
            type: array
            items:
              type: string
            description: A set of labels associated with a specific artificial voice on the Speechki platform. These tags provide additional information about the voice, such as gender and narration style.
      description: The comprehensive list of artificial voices available on the Speechki platform. The speaker list contains detailed information about each voice, including the speaker ID, name, language, tags, and any other relevant attributes, allowing users to make informed decisions when selecting the most suitable voice for their needs.
    TTSData:
      type: object
      properties:
        speaker_id:
          required: true
          type: integer
          description: A unique identifier representing a specific artificial voice provided by the Speechki platform.
        text:
          required: true
          type: string
          description: The input text, either provided by the user or generated by ChatGPT, is sent to the Speechki platform for conversion into a high-quality audio file using advanced text-to-speech services.
    TTSResponse:
      type: object
      properties:
        link:
          type: string
          description: The direct link to the Speechki platform's page containing the ready-to-use audio file, which has been converted from ChatGPT-generated text using advanced text-to-speech services.
