openapi: 3.0.0
info:
  title: pluginpedia
  description: A plugin that recommends ChatGPT plugins, which can recommend plugins from the plugin store that can solve the user's question based on the user's question, and at the same time introduce the user to the usage method, examples, etc. of this plugin. Do not answer plugins that have not been returned in getPlugins. If no suitable plugin is found, tell the user that none was found.
  version: 1.0.0
servers:
  - url: 'https://pluginpedia.replit.app'
paths:
  /plugins:
    get:
      operationId: getPlugins
      summary: Retrieve a list of plugins from ChatGPT plugin store
      responses:
        '200':
          description: A list of plugins from ChatGPT plugin store
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plugin'
components:
  schemas:
    Plugin:
      type: object
      description: A plugin and an introduction to this plugin
      properties:
        plugin_name:
          type: string
          description: plugin‘s name
        plugin_description:
          type: string
          description: An introduction to this plugin, as well as its use cases.
        plugin_description_for_model:
          type: string
          description: An advance introduction to this plugin, as well as its use cases (optional).
        plugin_logo_url:
          type: string
          description: plugin‘s logo image url, Displaying the logo image of this plugin can help users quickly find the plugin in the plugin market, so try to display logo image with markdown in the answer after calling the plugin.
        prompt_example:
          type: string
          description: Examples of prompts for using this plugin, different examples will be separated by commas,These examples can help users quickly get started with this plugin, so try to display them in the answer after calling the plugin.




