openapi: 3.0.1
info:
  title: property_search
  description: property searcher
  version: v1
servers:
  - url: https://propertysearch-5831-openai.langdock.com
paths:
  /search/query:
    post:
      operationId: getProperties
      summary: Get the properties based on the information provided by the user
      responses:
        '200':
          description: The found properties
          content:
            application/json:
              schema:
                type: array
                description: The list of all the properties found
                items:
                  type: object
                  description: ''
                  properties:
                    title:
                      type: string
                      description: >-
                        The title of the property which should be shown to the
                        user
                    price:
                      type: number
                      description: >-
                        The price of the property which should be shown to the
                        user
                    url:
                      type: string
                      description: >-
                        The url to the property, but the https:// needs to be
                        added at the beginning and also shown to the user
                    description:
                      type: string
                      description: The description of the property
                    id:
                      type: string
                      description: >-
                        The id of the property, that id should not be shown to
                        the user because it is only used in our system
                  required:
                    - title
                    - price
                    - url
                    - description
                    - id
      requestBody:
        description: The object used for the query
        required: true
        content:
          application/json:
            schema:
              type: object
              description: The object used for the query
              properties:
                user_prompt:
                  type: string
                  description: >-
                    This is the base query the user inputs that describes what
                    he is looking for
                ai_prompt:
                  type: string
                  description: This value should be left empty
                inquiry:
                  type: object
                  description: >-
                    Here are the informations of the property like type,
                    location, bedrooms, bathrooms, living area, plot size and
                    price
                  properties:
                    property_type:
                      type: string
                      description: >-
                        The type of the property, values like Villa, Apartment,
                        Flat, Finca
                    location:
                      type: string
                      description: The location where the property should be
                    bedrooms:
                      type: number
                      description: >-
                        The number of bedrooms wished, if nothing entered send
                        the default value
                    bathrooms:
                      type: number
                      description: >-
                        The number of bathrooms wished, if nothing entered send
                        the default value
                    livin_area:
                      type: number
                      description: >-
                        The size of the living area wished, it is in square
                        meters, if nothing entered send the default value
                    plot_size:
                      type: number
                      description: >-
                        The size of the plot size wished, it is in square
                        meters, if nothing entered send the default value
                    price:
                      type: number
                      description: >-
                        The wished price in Euro, this is a required information
                        and cant be left emtpy
                  required:
                    - property_type
                    - location
                    - bedrooms
                    - bathrooms
                    - livin_area
                    - plot_size
                    - price
              required:
                - user_prompt
                - ai_prompt
                - inquiry
components:
  schemas: {}
