openapi: 3.0.0
info:
  title: Flight Ticket And Hotel Search API
  description: Provide users customized itinarary planning and suitable recommendations of hotel and flights based on the real-time flight ticket and hotel info as per request.
  version: 1.0.0
servers:
  - url: https://www.trip.com/ai-resource
paths:
  /searchFlightTicket:
    post:
      summary: Get the flight info that matches user's request
      operationId: search_flight_ticket
      description: Get the flight info of price, origin, destination, travel date, take off time, arrival time, airline, flightway, seat grade, flight no., passenger type, transfer type, etc.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FlightQueryRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FlightQueryResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /searchHotel:
    post:
      summary: Get the hotel info that matches user's request
      operationId: search_hotel
      description: Get the hotel info of price, hotel name, room type, city, checkin date, checkout date, etc.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HotelQueryRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HotelQueryResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: string
    FlightQueryRequest:
      title: FlightQueryRequest
      required:
        - destinationCityCode
        - locale
      type: object
      properties:
        originCityCode:
          title: originCityCode
          type: string
        destinationCityCode:
          title: destinationCityCode
          type: string
        departureDate:
          title: departureDate
          type: string
        returnDate:
          title: returnDate
          type: string
        locale:
          title: locale
          type: string
        oneWayOrRoundTrip:
          title: oneWayOrRoundTrip
          type: string
          enum:
            - OW
            - RT
    FlightQueryResponse:
      title: FlightQueryResponse
      required:
        - bookFlightLink
      type: object
      properties:
        originCityCode:
          title: originCityCode
          type: string
        destinationCityCode:
          title: destinationCityCode
          type: string
        oneWayOrRoundTrip:
          title: oneWayOrRoundTrip
          type: string
          enum:
            - OW
            - RT
        departureDate:
          title: departureDate
          type: string
        returnDate:
          title: returnDate
          type: string
        bookFlightLink:
          title: bookFlightLink
          type: string
        recommendedListOfOtherFlights:
          title: recommendedListOfOtherFlights
          type: array
          items:
            $ref: "#/components/schemas/Flight"
    Flight:
      title: Flight
      type: object
      properties:
        flightTicketLink:
          title: flightTicketLink
          type: string
        oneWayOrRoundTrip:
          title: oneWayOrRoundTrip
          type: string
          enum:
            - OW
            - RT
          default: OW
        numberOfStops:
          title: numberOfStops
          type: integer
        flightDuration:
          title: flightDuration
          type: string
        pricePerTicket:
          title: pricePerTicket
          type: string
        currency:
          title: currency
          type: string
        departureTime:
          title: departureTime
          type: string
        arrivalTime:
          title: arrivalTime
          type: string
        airline:
          title: airline
          type: string
        departureAirport:
          title: departureAirport
          type: string
        arrivalAirport:
          title: arrivalAirport
          type: string
        flightNumber:
          title: flightNumber
          type: string
        returnDepartureTime:
          title: returnDepartureTime
          type: string
        returnArrivalTime:
          title: returnArrivalTime
          type: string
        returnAirline:
          title: returnAirline
          type: string
        returnDepartureAirport:
          title: returnDepartureAirport
          type: string
        returnArrivalAirport:
          title: returnArrivalAirport
          type: string
        returnFlightNumber:
          title: returnFlightNumber
          type: string
        returnNumberOfStops:
          title: returnNumberOfStops
          type: integer
        returnFlightDuration:
          title: returnFlightDuration
          type: string
    HotelQueryRequest:
      title: HotelQueryRequest
      required:
        - cityName
        - locale
      type: object
      properties:
        cityName:
          title: cityName
          type: string
        topHotel:
          title: topHotel
          type: integer
        locale:
          title: locale
          type: string
        checkIn:
          title: checkIn
          type: date
        checkOut:
          title: checkOut
          type: date
    HotelQueryResponse:
      title: HotelQueryResponse
      required:
        - hotelList
      type: object
      properties:
        hotelList:
          title: HotelList
          type: array
          items:
            $ref: "#/components/schemas/Hotel"
    Hotel:
      title: Hotel
      type: object
      properties:
        hotelName:
          title: HotelName
          type: string
        hotelDescription:
          title: HotelDescription
          type: string
        hotelCurrency:
          title: HotelCurrency
          type: string
        hotelPrice:
          title: HotelPrice
          type: number
        hotelLink:
          title: HotelLink
          type: string
        hotelAddress:
          title: hotelAddress
          type: string
        openYear:
          title: openYear
          type: string
          description: The opening year of the hotel
        renovationYear:
          title: renovationYear
          type: string
          description: The renovation year of the hotel
        score:
          title: score
          type: string
        numberOfReviews:
          title: numberOfReviews
          type: integer
          description: The number of reviews for the hotel.
        numberOfFavorites:
          title: numberOfFavorites
          type: string
          description: The number of times the hotel has been added to favorites
        star:
          title: star
          type: integer
        hotelFeatureTagList:
          title: hotelFeatureTagList
          type: array
          items:
            type: string