openapi: 3.0.1
info:
  title: Academic Plugin
  description:  >
    A plugin that allows the user to search academic papers using ChatGPT. It provides endpoints for searching papers, searching papers with PDF links, and searching papers by id.  This plugin allows you to search for academic papers in the arXiv database. You can use atomic conditions and boolean assembly in your search queries. You can use atomic conditions and boolean assembly in your search queries. Always consider using atomic conditions to refine your search. Each article is divided up into a number of fields that can individually be searched. Here are the field prefixes you can use in your search queries: 'ti' for Title, 'au' for Author, 'abs' for Abstract, 'co' for Comment, 'jr' for Journal Reference, 'cat' for Subject Category, 'rn' for Report Number, 'id' for Id (use route /search/id instead), 'all' for all of the above. You can also use boolean operators like AND, OR, ANDNOT in your queries. For example, 'au:del_maestro+AND+ti:checkerboard' will return papers by the author Del Maestro with 'checkerboard' in the title. You can also group your queries using parentheses and double quotes. For example, 'au:del_maestro+AND+ti:%22quantum+criticality%22' will return papers by the author Del Maestro with 'quantum criticality' in the title. You can also use abbreviations for arXiv subject categories in your queries, like 'stat.AP' for Statistics - Applications, 'cs.AI' for Computer Science - Artificial Intelligence, and so on.
    
    For the search query, you can use atomic conditions and boolean assembly. Here are some examples:
    
    - Atomic conditions: `condition("au", "Balents Leon") → "au:\"Balents Leon\""`
    - Boolean assembly: `and(cond1, cond2) → "$(cond1) AND $(cond2)"`
    
    You can also use the following prefixes in your queries:
    
    - ti: Title
    - au: Author
    - abs: Abstract
    - co: Comment
    - jr: Journal Reference
    - cat: Subject Category
    - rn: Report Number
    - id: Id (use id_list instead)
    - all: All of the above
    
  version: 'v1'
servers:
  - url: https://xapi.lihaorui.com
paths:
  /search:
    post:
      operationId: search_papers
      summary: Search for academic papers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Paper'
        "500":
          description: Internal Server Error
  /search/pdf:
    post:
      operationId: search_papers_with_pdf
      summary: Search for academic papers with PDF links
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Paper'
        "500":
          description: Internal Server Error
  /search/id:
    post:
      operationId: search_papers_by_id
      summary: Search for academic papers by id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchByIdRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Paper'
        "500":
          description: Internal Server Error
components:
  schemas:
    SearchRequest:
      type: object
      required:
      - query
      - max_results
      properties:
        query:
          type: string
          description: The search query.
        max_results:
          type: integer
          description: The maximum number of search results to return.
    SearchByIdRequest:
      type: object
      required:
      - id_list
      - max_results
      properties:
        id_list:
          type: array
          items:
            type: string
          description: The list of ids to search for.
        max_results:
          type: integer
          description: The maximum number of search results to return.
    Paper:
      type: object
      properties:
        entry_id:
          type: string
        updated:
          type: string
        published:
          type: string
        title:
          type: string
        authors:
          type: array
          items:
            type: string
        summary:
          type: string
        comment:
          type: string
        journal_ref:
          type: string
        doi:
          type: string
        primary_category:
          type: string
        categories:
          type: array
          items:
            type: string
        links:
          type: array
          items:
            type: string
        pdf_url:
          type: string
